version: 0.0
os: linux
files:
  - source: /
    destination: /opt/xeniuser/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: root

