version: 0.0
os: linux
files:
  - source: /
    destination: /opt/xeniuser/node-app/
    overwrite: true
permissions:
  - object: /opt/xeniuser/node-app/
    pattern: "**"
    owner: xeniuser
    group: xeniusergroup
    mode: 755
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: xeniuser
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: xeniuser

