name: "Build and deploy to EC2"

on:
  push:
    branches:
      - staging
jobs:
  init:
    runs-on: ubuntu-latest
    name: Setup XeniApp Deployment Environment
    steps:
      - name: Set env to dev
        if: endsWith(github.ref, '/staging')
        run: |
          echo "XENIENV_NAME=dev" >> $GITHUB_ENV
      - name: Set env to prod
        if: endsWith(github.ref, '/main')
        run: |
          echo "XENIENV_NAME=prod" >> $GITHUB_ENV
      - name: Set Envrironment Variables
        run: |
          echo "APP_NAME=Xeniapp-backend-${{ env.XENIENV_NAME }}" >> $GITHUB_ENV
          echo "S3-BUCKET=xeniapp-backend-codedeploy-${{ env.XENIENV_NAME }}" >> $GITHUB_ENV
          echo "S3-FILENAME=${{ env.XENIENV_NAME }}/backend-$(date --iso-8601=seconds)Z" >> $GITHUB_ENV
          echo "DEPLOY-GROUP=Xeniapp-backend-dep-group-${{ env.XENIENV_NAME }}" >> $GITHUB_ENV


